### ISSUE TITLE
Create a release pipeline

### ISSUE THREAD

**Issue by rmcdaniel** [serverlessworkflow/sdk-php#5]
I submitted https://packagist.org/packages/serverlessworkflow/sdk but it needs to be configured with a webhook so that new tagged releases in GitHub will automatically be reflected there. (EDIT: webhook added)

As far as a process for tagging new releases in GitHub, do we want to do that manually?

@cdavernas @ricardozanini

**Comment by rmcdaniel** [comment]
This is done for now with manual tagging.

**Comment by cdavernas** [comment]
@rmcdaniel Well, that's what I do for the NET SDK sor far. 

Ideally, we should be using automatic, semantic versioning. 

In the best of world, the semantic version should be computed using keywords in commit messages, such as is done by https://github.com/cbcrouse/Versioning.NET:

```
fix(...): A needed fix
feat(...): A cool feature
...
```
